services:
  db-seed:
    build:
      context: ../..
      dockerfile: ./Dockerfile.dev
    depends_on:
      shared-database:
        condition: service_healthy
    command: pnpm db:seed
    networks:
      - wallet-backend